name: CI
on:
  push:
    branches:
      - canary
jobs:
  build-test-and-deploy:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Install
      - run: yarn bootstrap
        name: Bootstrap
      - run: yarn test
        name: Test
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> .npmrc
        name: Configure NPM user
      - run: yarn publish-ci
        name: Publish CI tag to npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
